version: '1.0'

services:
  nginx:
    image: nginx-i
    container_name: ${NGINX_HOST}
    network_mode: host
    build:
      context: nginx
      dockerfile: Dockerfile
      args:
        - ENABLED_MODULES=rtmp
    env_file: .env
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${RTMP_PORT}:${RTMP_PORT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/rtmp.conf:/etc/nginx/conf.d/rtmp.conf
      - ./nginx/http.conf:/etc/nginx/conf.d/http.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
